import { type NextPage } from "next";

import { Header } from "../components/Header";

import Head from "next/head";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Notetaker</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
      </main>
		</>
	);
};

export default Home;
